# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/max/Documents/MD/phazeMod/ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(45, 50, 80);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 12, 0, 12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grp_wid = QtWidgets.QWidget(self.widget)
        self.grp_wid.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grp_wid.setStyleSheet("background-color: rgb(45, 50, 80);")
        self.grp_wid.setObjectName("grp_wid")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grp_wid)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.time_wid = QtWidgets.QWidget(self.grp_wid)
        self.time_wid.setStyleSheet("background-color: rgb(66, 71, 105);")
        self.time_wid.setObjectName("time_wid")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.time_wid)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.time_grp = QtWidgets.QGraphicsView(self.time_wid)
        self.time_grp.setObjectName("time_grp")
        self.verticalLayout_3.addWidget(self.time_grp)
        self.verticalLayout_2.addWidget(self.time_wid)
        self.spec_wid = QtWidgets.QWidget(self.grp_wid)
        self.spec_wid.setMinimumSize(QtCore.QSize(100, 200))
        self.spec_wid.setStyleSheet("background-color: rgb(66, 71, 105);")
        self.spec_wid.setObjectName("spec_wid")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.spec_wid)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.spec_grp = QtWidgets.QGraphicsView(self.spec_wid)
        self.spec_grp.setObjectName("spec_grp")
        self.verticalLayout_4.addWidget(self.spec_grp)
        self.verticalLayout_2.addWidget(self.spec_wid)
        self.horizontalLayout.addWidget(self.grp_wid)
        self.btn_wid = QtWidgets.QWidget(self.widget)
        self.btn_wid.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_wid.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_wid.setStyleSheet("background-color: rgb(66, 71, 105);")
        self.btn_wid.setObjectName("btn_wid")
        self.set_btn = QtWidgets.QPushButton(self.btn_wid)
        self.set_btn.setGeometry(QtCore.QRect(10, 480, 181, 51))
        self.set_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 177, 122);\n"
"    border:1px solid;\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 177, 122);\n"
"    border-radius:7px;\n"
"}")
        self.set_btn.setAutoDefault(False)
        self.set_btn.setDefault(False)
        self.set_btn.setObjectName("set_btn")
        self.coeff_dial = QtWidgets.QDial(self.btn_wid)
        self.coeff_dial.setGeometry(QtCore.QRect(10, 10, 101, 101))
        self.coeff_dial.setMaximum(10)
        self.coeff_dial.setPageStep(1)
        self.coeff_dial.setObjectName("coeff_dial")
        self.checkBox = QtWidgets.QCheckBox(self.btn_wid)
        self.checkBox.setGeometry(QtCore.QRect(20, 390, 87, 20))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("background-color: rgb(103, 111, 157);\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"border-radius:3px;")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.btn_wid)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 430, 87, 20))
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setStyleSheet("background-color: rgb(103, 111, 157);\n"
"border-radius:3px;\n"
"")
        self.checkBox_2.setObjectName("checkBox_2")
        self.spinBox = QtWidgets.QSpinBox(self.btn_wid)
        self.spinBox.setGeometry(QtCore.QRect(30, 340, 48, 24))
        self.spinBox.setStyleSheet("background-color: rgb(103, 111, 157);\n"
"border:3px;")
        self.spinBox.setObjectName("spinBox")
        self.lcdNumber = QtWidgets.QLCDNumber(self.btn_wid)
        self.lcdNumber.setGeometry(QtCore.QRect(90, 130, 64, 23))
        self.lcdNumber.setProperty("value", 1.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.btn_wid)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "phazeMod"))
        self.set_btn.setText(_translate("MainWindow", "Set"))
        self.checkBox.setText(_translate("MainWindow", "Sin"))
        self.checkBox_2.setText(_translate("MainWindow", "Cos"))
